name: 'Setup blup (Blender Version Manager)'
description: 'Install blup and manage Blender versions with built-in caching and security check.'
author: 'unclepomedev'
branding:
  icon: 'box'
  color: 'orange'

inputs:
  blup-version:
    description: 'Version of blup to install (e.g. "v0.1.0" or "latest")'
    required: false
    default: 'latest'
  blender-version:
    description: 'Blender version to install. If empty, checks for .blender-version file.'
    required: false
  daily:
    description: 'Install from daily/experimental builds (adds --daily flag)'
    required: false
    default: 'false'
  cache:
    description: 'Enable caching for Blender binaries (true/false)'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    # ----------------------------------------------------------------
    # 1. Install blup
    # ----------------------------------------------------------------
    - name: Install blup (Unix)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        set -euo pipefail
        v='${{ inputs.blup-version }}'
        if [ "$v" = "latest" ] || [ -z "$v" ]; then
          base_url='https://github.com/unclepomedev/blup/releases/latest/download'
        else
          base_url="https://github.com/unclepomedev/blup/releases/download/$v"
        fi
        
        script_url="${base_url}/blup-installer.sh"
        checksum_url="${base_url}/blup-installer.sh.sha256"
        
        echo "Downloading installer and checksum..."
        echo "  Script: $script_url"
        
        curl --proto '=https' --tlsv1.2 -fsSL --retry 3 --retry-connrefused "$script_url" -o blup-installer.sh
        curl --proto '=https' --tlsv1.2 -fsSL --retry 3 --retry-connrefused "$checksum_url" -o blup-installer.sh.sha256
        
        echo "Verifying checksum..."
        # sha256sum (Linux) or shasum (macOS)
        if command -v sha256sum >/dev/null 2>&1; then
          sha256sum -c blup-installer.sh.sha256
        elif command -v shasum >/dev/null 2>&1; then
          shasum -a 256 -c blup-installer.sh.sha256
        else
          echo "::error::Neither sha256sum nor shasum found for verification."
          exit 1
        fi
        
        echo "Checksum verified. Executing installer..."
        chmod +x blup-installer.sh
        ./blup-installer.sh
        echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"

    - name: Install blup (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $v = '${{ inputs.blup-version }}'
        if ($v -eq 'latest' -or [string]::IsNullOrEmpty($v)) {
          $baseUrl = 'https://github.com/unclepomedev/blup/releases/latest/download'
        } else {
          $baseUrl = "https://github.com/unclepomedev/blup/releases/download/$v"
        }
        
        $scriptUrl = "$baseUrl/blup-installer.ps1"
        $checksumUrl = "$baseUrl/blup-installer.ps1.sha256"
        
        $scriptPath = Join-Path $env:RUNNER_TEMP 'blup-installer.ps1'
        $checksumPath = Join-Path $env:RUNNER_TEMP 'blup-installer.ps1.sha256'
        
        Write-Host "Downloading installer and checksum..."
        try {
            Invoke-WebRequest -Uri $scriptUrl -OutFile $scriptPath -ErrorAction Stop
            Invoke-WebRequest -Uri $checksumUrl -OutFile $checksumPath -ErrorAction Stop
        } catch {
            Write-Error "Failed to download blup installer or checksum from $baseUrl"
            exit 1
        }
        
        Write-Host "Verifying checksum..."
        $checksumContent = Get-Content -Path $checksumPath -Raw
        $expectedHash = ($checksumContent -split '\s+')[0].Trim()
        
        $computedHash = (Get-FileHash -Path $scriptPath -Algorithm SHA256).Hash
        
        if ($expectedHash.ToLower() -ne $computedHash.ToLower()) {
             Write-Error "Checksum verification failed!"
             Write-Error "Expected: $expectedHash"
             Write-Error "Computed: $computedHash"
             exit 1
        }
        
        Write-Host "Checksum verified. Executing installer..."
        
        $LASTEXITCODE = 0
        & $scriptPath
        if (-not $?) {
          Write-Error "blup installer script failed (PowerShell execution error)"
          exit 1
        }
        if ($LASTEXITCODE -ne 0) {
          Write-Error "blup installer failed with exit code $LASTEXITCODE"
          exit $LASTEXITCODE
        }
        "$env:USERPROFILE\.cargo\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    # ----------------------------------------------------------------
    # 2. Determine Cache Paths & Resolve Version
    # ----------------------------------------------------------------
    - name: Resolve Version and Cache Paths (Unix)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        # Set Cache Path
        if [ "${{ runner.os }}" == "Linux" ]; then
           echo "BLUP_CACHE_PATH=$HOME/.local/share/blup/versions" >> $GITHUB_ENV
        elif [ "${{ runner.os }}" == "macOS" ]; then
           echo "BLUP_CACHE_PATH=$HOME/Library/Application Support/blup/versions" >> $GITHUB_ENV
        fi

        # Resolve Version using blup
        INPUT_VERSION="${{ inputs.blender-version }}"
        if [ -n "$INPUT_VERSION" ]; then
          RESOLVED=$(blup resolve "$INPUT_VERSION" 2>/dev/null || true)
        else
          RESOLVED=$(blup resolve 2>/dev/null || true)
        fi
        
        if [ -n "$RESOLVED" ]; then
          echo "Detected version: $RESOLVED"
          echo "RESOLVED_BLENDER_VERSION=$RESOLVED" >> $GITHUB_ENV
        else
          if [ -n "$INPUT_VERSION" ]; then
            echo "::error::Unable to resolve Blender version: $INPUT_VERSION"
            exit 1
          fi
          echo "No Blender version specified or found. Skipping installation."
        fi

    - name: Resolve Version and Cache Paths (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        # Set Cache Path
        echo "BLUP_CACHE_PATH=$env:LOCALAPPDATA\blup\versions" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

        # Resolve Version using blup
        $resolved = $null
        $inputVer = "${{ inputs.blender-version }}"
        try {
            if (-not [string]::IsNullOrEmpty($inputVer)) {
                $resolved = blup resolve $inputVer
            } else {
                $resolved = blup resolve
            }
        } catch {
            Write-Host "No version resolved via blup."
        }

        if (-not [string]::IsNullOrEmpty($resolved)) {
            $resolved = $resolved.Trim()
            Write-Host "Detected version: $resolved"
            "RESOLVED_BLENDER_VERSION=$resolved" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        } elseif (-not [string]::IsNullOrEmpty($inputVer)) {
            Write-Error "Unable to resolve Blender version: $inputVer"
            exit 1
        } else {
            Write-Host "No Blender version specified or found. Skipping installation."
        }

    # ----------------------------------------------------------------
    # 3. Cache Restore
    # ----------------------------------------------------------------
    - name: Restore Blender Cache
      if: inputs.cache == 'true' && env.RESOLVED_BLENDER_VERSION != ''
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
      id: blender-cache
      with:
        path: ${{ env.BLUP_CACHE_PATH }}
        key: blup-blender-${{ runner.os }}-${{ env.RESOLVED_BLENDER_VERSION }}-daily-${{ inputs.daily }}
        restore-keys: |
          blup-blender-${{ runner.os }}-

    # ----------------------------------------------------------------
    # 4. Install & Set Default Blender
    # ----------------------------------------------------------------
    - name: Install Resolved Blender Version (Unix)
      if: env.RESOLVED_BLENDER_VERSION != '' && runner.os != 'Windows'
      shell: bash
      env:
        IS_DAILY: ${{ inputs.daily }}
      run: |
        set -euo pipefail
        
        ARGS=("--default")
        if [ "$IS_DAILY" == "true" ]; then
          ARGS+=("--daily")
        fi
        
        blup install "$RESOLVED_BLENDER_VERSION" "${ARGS[@]}"

    - name: Install Resolved Blender Version (Windows)
      if: env.RESOLVED_BLENDER_VERSION != '' && runner.os == 'Windows'
      shell: pwsh
      env:
        IS_DAILY: ${{ inputs.daily }}
      run: |
        $argsList = @($env:RESOLVED_BLENDER_VERSION, "--default")
        if ($env:IS_DAILY -eq 'true') { $argsList += "--daily" }
        
        & blup install $argsList
        
        if ($LASTEXITCODE -ne 0) {
          Write-Error "blup install failed with exit code $LASTEXITCODE"
          exit $LASTEXITCODE
        }