name: 'Setup blup (Blender Version Manager)'
description: 'Install blup and manage Blender versions with caching support.'
author: 'unclepomedev'
branding:
  icon: 'box'
  color: 'orange'

inputs:
  blup-version:
    description: 'Version of blup to install (e.g. "v0.1.0" or "latest")'
    required: false
    default: 'latest'
  blender-version:
    description: 'Blender version to install. If empty, checks for .blender-version file.'
    required: false
  daily:
    description: 'Install from daily/experimental builds (adds --daily flag)'
    required: false
    default: 'false'
  cache:
    description: 'Enable caching for Blender binaries (true/false)'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    # ----------------------------------------------------------------
    # 1. Install blup
    # ----------------------------------------------------------------
    - name: Install blup (Unix)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        set -euo pipefail
        v='${{ inputs.blup-version }}'
        if [ "$v" = "latest" ] || [ -z "$v" ]; then
          url='https://github.com/unclepomedev/blup/releases/latest/download/blup-installer.sh'
        else
          url="https://github.com/unclepomedev/blup/releases/download/$v/blup-installer.sh"
        fi
        echo "Downloading installer from: $url"
        curl --proto '=https' --tlsv1.2 -fsSL --retry 3 --retry-connrefused "$url" -o blup-installer.sh
        chmod +x blup-installer.sh
        ./blup-installer.sh
        echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"

    - name: Install blup (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $v = '${{ inputs.blup-version }}'
        if ($v -eq 'latest' -or [string]::IsNullOrEmpty($v)) {
          $url = 'https://github.com/unclepomedev/blup/releases/latest/download/blup-installer.ps1'
        } else {
          $url = "https://github.com/unclepomedev/blup/releases/download/$v/blup-installer.ps1"
        }
        echo "Downloading installer from: $url"
        $dst = Join-Path $env:RUNNER_TEMP 'blup-installer.ps1'
        try {
            Invoke-WebRequest -Uri $url -OutFile $dst -ErrorAction Stop
        } catch {
            Write-Error "Failed to download blup installer from $url"
            exit 1
        }
        
        $LASTEXITCODE = 0
        & $dst
        if (-not $?) {
          Write-Error "blup installer script failed (PowerShell execution error)"
          exit 1
        }
        if ($LASTEXITCODE -ne 0) {
          Write-Error "blup installer failed with exit code $LASTEXITCODE"
          exit $LASTEXITCODE
        }
        "$env:USERPROFILE\.cargo\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    # ----------------------------------------------------------------
    # 2. Determine Cache Paths & Resolve Version
    # ----------------------------------------------------------------
    - name: Resolve Version and Cache Paths (Unix)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        # Set Cache Path
        if [ "${{ runner.os }}" == "Linux" ]; then
           echo "BLUP_CACHE_PATH=$HOME/.local/share/blup/versions" >> $GITHUB_ENV
        elif [ "${{ runner.os }}" == "macOS" ]; then
           echo "BLUP_CACHE_PATH=$HOME/Library/Application Support/blup/versions" >> $GITHUB_ENV
        fi

        # Resolve Version using blup
        RESOLVED=$(blup resolve ${{ inputs.blender-version }} 2>/dev/null || true)
        
        if [ -n "$RESOLVED" ]; then
          echo "Detected version: $RESOLVED"
          echo "RESOLVED_BLENDER_VERSION=$RESOLVED" >> $GITHUB_ENV
        else
          echo "No Blender version specified or found. Skipping installation."
        fi

    - name: Resolve Version and Cache Paths (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        # Set Cache Path
        echo "BLUP_CACHE_PATH=$env:LOCALAPPDATA\blup\versions" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

        # Resolve Version using blup
        $resolved = $null
        try {
            $inputVer = "${{ inputs.blender-version }}"
            if (-not [string]::IsNullOrEmpty($inputVer)) {
                $resolved = blup resolve $inputVer
            } else {
                $resolved = blup resolve
            }
        } catch {
            Write-Host "No version resolved via blup."
        }

        if (-not [string]::IsNullOrEmpty($resolved)) {
            $resolved = $resolved.Trim()
            Write-Host "Detected version: $resolved"
            "RESOLVED_BLENDER_VERSION=$resolved" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        } else {
            Write-Host "No Blender version specified or found. Skipping installation."
        }

    # ----------------------------------------------------------------
    # 3. Cache Restore
    # ----------------------------------------------------------------
    - name: Restore Blender Cache
      if: inputs.cache == 'true' && env.RESOLVED_BLENDER_VERSION != ''
      uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5
      id: blender-cache
      with:
        path: ${{ env.BLUP_CACHE_PATH }}
        key: blup-blender-${{ runner.os }}-${{ env.RESOLVED_BLENDER_VERSION }}-daily-${{ inputs.daily }}
        restore-keys: |
          blup-blender-${{ runner.os }}-

    # ----------------------------------------------------------------
    # 4. Install & Set Default Blender
    # ----------------------------------------------------------------
    - name: Install Resolved Blender Version (Unix)
      if: env.RESOLVED_BLENDER_VERSION != '' && runner.os != 'Windows'
      shell: bash
      env:
        IS_DAILY: ${{ inputs.daily }}
      run: |
        set -euo pipefail
        
        ARGS=("--default")
        if [ "$IS_DAILY" == "true" ]; then
          ARGS+=("--daily")
        fi
        
        blup install "$RESOLVED_BLENDER_VERSION" "${ARGS[@]}"

    - name: Install Resolved Blender Version (Windows)
      if: env.RESOLVED_BLENDER_VERSION != '' && runner.os == 'Windows'
      shell: pwsh
      env:
        IS_DAILY: ${{ inputs.daily }}
      run: |
        $argsList = @($env:RESOLVED_BLENDER_VERSION, "--default")
        if ($env:IS_DAILY -eq 'true') { $argsList += "--daily" }
        
        & blup install $argsList
        
        if ($LASTEXITCODE -ne 0) {
          Write-Error "blup install failed with exit code $LASTEXITCODE"
          exit $LASTEXITCODE
        }