name: 'Setup blup (Blender Version Manager)'
description: 'Install blup and manage Blender versions with caching support.'
author: 'unclepomedev'
branding:
  icon: 'box'
  color: 'orange'

inputs:
  blup-version:
    description: 'Version of blup to install (e.g. "v0.0.8" or "latest")'
    required: false
    default: 'latest'
  blender-version:
    description: 'Blender version to install and set as default. If empty, only blup is installed.'
    required: false
  daily:
    description: 'Install from daily/experimental builds (adds --daily flag)'
    required: false
    default: 'false'
  cache:
    description: 'Enable caching for Blender binaries (true/false)'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    # ----------------------------------------------------------------
    # 1. Install blup (Safe Mode: No Pipe)
    # ----------------------------------------------------------------
    - name: Install blup (Unix)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        set -euo pipefail
        
        v='${{ inputs.blup-version }}'
        if [ "$v" = "latest" ] || [ -z "$v" ]; then
          url='https://github.com/unclepomedev/blup/releases/latest/download/blup-installer.sh'
        else
          url="https://github.com/unclepomedev/blup/releases/download/$v/blup-installer.sh"
        fi
        
        echo "Downloading installer from: $url"
        curl --proto '=https' --tlsv1.2 -fsSL --retry 3 --retry-connrefused "$url" -o blup-installer.sh
        
        chmod +x blup-installer.sh
        ./blup-installer.sh
        
        echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"

    - name: Install blup (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $v = '${{ inputs.blup-version }}'
        if ($v -eq 'latest' -or [string]::IsNullOrEmpty($v)) {
          $url = 'https://github.com/unclepomedev/blup/releases/latest/download/blup-installer.ps1'
        } else {
          $url = "https://github.com/unclepomedev/blup/releases/download/$v/blup-installer.ps1"
        }
        
        Write-Host "Downloading installer from: $url"
        $dst = Join-Path $env:RUNNER_TEMP 'blup-installer.ps1'
        
        try {
            Invoke-WebRequest -UseBasicParsing -Uri $url -OutFile $dst -ErrorAction Stop
        } catch {
            Write-Error "Failed to download blup installer from $url"
            exit 1
        }

        & $dst
        
        "$env:USERPROFILE\.cargo\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    # ----------------------------------------------------------------
    # 2. Determine Cache Paths
    # ----------------------------------------------------------------
    - name: Set Cache Path Env (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: echo "BLUP_CACHE_PATH=$HOME/.local/share/blup/versions" >> $GITHUB_ENV

    - name: Set Cache Path Env (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: echo "BLUP_CACHE_PATH=$HOME/Library/Application Support/blup/versions" >> $GITHUB_ENV

    - name: Set Cache Path Env (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: echo "BLUP_CACHE_PATH=$env:LOCALAPPDATA\blup\versions" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    # ----------------------------------------------------------------
    # 3. Cache Restore
    # ----------------------------------------------------------------
    - name: Restore Blender Cache
      if: inputs.cache == 'true' && inputs.blender-version != ''
      uses: actions/cache@v5
      id: blender-cache
      with:
        path: ${{ env.BLUP_CACHE_PATH }}
        key: blup-blender-${{ runner.os }}-${{ inputs.blender-version }}-daily-${{ inputs.daily }}
        restore-keys: |
          blup-blender-${{ runner.os }}-

    # ----------------------------------------------------------------
    # 4. Install & Set Default Blender (Unix)
    # ----------------------------------------------------------------
    - name: Install Requested Blender Version (Unix)
      if: inputs.blender-version != '' && runner.os != 'Windows'
      shell: bash
      env:
        BLENDER_VERSION: ${{ inputs.blender-version }}
        IS_DAILY: ${{ inputs.daily }}
      run: |
        ARGS=""
        if [ "$IS_DAILY" == "true" ]; then
          ARGS="--daily"
        fi
        
        blup install $BLENDER_VERSION $ARGS
        INSTALLED_NAME=$(ls -t "$BLUP_CACHE_PATH" | head -n1)
        echo "Resolved installed version: $INSTALLED_NAME"
        
        blup default "$INSTALLED_NAME"

    # ----------------------------------------------------------------
    # 4. Install & Set Default Blender (Windows)
    # ----------------------------------------------------------------
    - name: Install Requested Blender Version (Windows)
      if: inputs.blender-version != '' && runner.os == 'Windows'
      shell: pwsh
      env:
        BLENDER_VERSION: ${{ inputs.blender-version }}
        IS_DAILY: ${{ inputs.daily }}
      run: |
        $argsList = @()
        if ($env:IS_DAILY -eq 'true') { $argsList += "--daily" }
        
        & blup install $env:BLENDER_VERSION $argsList
        $latest = Get-ChildItem -Path "$env:BLUP_CACHE_PATH" -Directory | Sort-Object LastWriteTime -Descending | Select-Object -First 1
        Write-Host "Resolved installed version: $($latest.Name)"
        
        blup default $latest.Name