name: 'Setup blup (Blender Version Manager)'
description: 'Install blup and manage Blender versions with caching support.'
author: 'unclepomedev'
branding:
  icon: 'box'
  color: 'orange'

inputs:
  blup-version:
    description: 'Version of blup to install (default: latest)'
    required: false
    default: 'latest'
  blender-version:
    description: 'Blender version to install and set as default (e.g. "5.0.1", "daily"). If empty, only blup is installed.'
    required: false
  cache:
    description: 'Enable caching for Blender binaries (true/false)'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    # ----------------------------------------------------------------
    # 1. Install blup
    # ----------------------------------------------------------------
    - name: Install blup (Unix)
      if: runner.os != 'Windows'
      shell: bash
      env:
        BLUP_VERSION: ${{ inputs.blup-version }}
      run: |
        if [ "$BLUP_VERSION" = "latest" ] || [ -z "$BLUP_VERSION" ]; then
          URL="https://github.com/unclepomedev/blup/releases/latest/download/blup-installer.sh"
        else
          URL="https://github.com/unclepomedev/blup/releases/download/v${BLUP_VERSION}/blup-installer.sh"
        fi
        
        echo "Installing blup from: $URL"
        curl --proto '=https' --tlsv1.2 -LsSf "$URL" | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install blup (Windows)
      if: runner.os == 'Windows'
      shell: powershell
      env:
        BLUP_VERSION: ${{ inputs.blup-version }}
      run: |
        $ver = $env:BLUP_VERSION
        if ($ver -eq "latest" -or [string]::IsNullOrEmpty($ver)) {
            $url = "https://github.com/unclepomedev/blup/releases/latest/download/blup-installer.ps1"
        } else {
            $url = "https://github.com/unclepomedev/blup/releases/download/v$ver/blup-installer.ps1"
        }

        Write-Host "Installing blup from: $url"
        powershell -ExecutionPolicy Bypass -c "irm $url | iex"
        echo "$env:USERPROFILE\.cargo\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    # ----------------------------------------------------------------
    # 2. Determine Cache Paths (OS dependent)
    # ----------------------------------------------------------------
    - name: Set Cache Path Env (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: echo "BLUP_CACHE_PATH=$HOME/.local/share/blup/versions" >> $GITHUB_ENV

    - name: Set Cache Path Env (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: echo "BLUP_CACHE_PATH=$HOME/Library/Application Support/blup/versions" >> $GITHUB_ENV

    - name: Set Cache Path Env (Windows)
      if: runner.os == 'Windows'
      shell: powershell
      run: echo "BLUP_CACHE_PATH=$env:LOCALAPPDATA\blup\versions" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    # ----------------------------------------------------------------
    # 3. Cache Restore
    # ----------------------------------------------------------------
    - name: Restore Blender Cache
      if: inputs.cache == 'true' && inputs.blender-version != ''
      uses: actions/cache@v4
      id: blender-cache
      with:
        path: ${{ env.BLUP_CACHE_PATH }}
        key: blup-blender-${{ runner.os }}-${{ inputs.blender-version }}
        restore-keys: |
          blup-blender-${{ runner.os }}-

    # ----------------------------------------------------------------
    # 4. Install & Set Default Blender
    # ----------------------------------------------------------------
    - name: Install Requested Blender Version
      if: inputs.blender-version != ''
      shell: bash
      run: |
        blup install ${{ inputs.blender-version }}
        blup default ${{ inputs.blender-version }}